name: Release

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Release
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1

    - name: Create release using semantic-release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      with:
        semantic_version: 17.1.1
        extra_plugins: |
          @semantic-release/changelog@5.0.1
          @semantic-release/git@9.0
      env:
        # GITHUB_TOKEN is added automatically by GitHub
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create zip
      run: |
        rm -rf now-playing
        rm -rf now-playing.widget
        rm now-playing.widget.zip
        mkdir now-playing
        cp index.jsx now-playing
        cp script.scpt now-playing
        cp current_track.py now-playing
        cp README.md now-playing
        zip -r now-playing.widget.zip now-playing

    - name: Push updated zip
      uses: EndBug/add-and-commit@v5
      with:
        add: 'now-playing.widget.zip'
        branch: master
        message: 'chore(release): update zip file [skip ci]'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

